name: income_expenditure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  floor: ^1.5.0
  sqflite: ^2.4.0
  get: ^4.6.6
  flutter_jalali_date_picker: ^2.2.3
  intl: ^0.19.0
  shamsi_date: ^1.0.4
  awesome_snackbar_content: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.5.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

flutter_intl:
  enabled: true
